INACTIVITY_THRESHOLD_SECONDS = 10
SEGMENT_WINDOW_SECONDS = 30
MIN_EVENT_DURATION_SECONDS = 0.4
CONFIDENCE_THRESHOLD = 0.3
YAWN_MOUTH_RATIO = 0.35
MOTION_THRESHOLD = 1.0
FACE_VISIBILITY_RATIO = 0.7

SUPPORTED_FORMATS = [".mp4", ".webm", ".avi"]
OUTPUT_FORMAT = "json"

SAVE_UNDETECTED_FRAMES = True
UNDETECTED_OUTPUT_DIR = "debug/no_face_frames"
MAX_SAVED_UNDETECTED = 30
SAVE_EVERY_NTH_UNDETECTED = 15
RESIZE_WIDTH = 640
RESIZE_HEIGHT = 480